# Render the Helm chart at deploy/helm/procurement-spend-dashboard/ into
# deployer-apps/<tenant>/<env>/manifests/ for each tenant+env we ship.
# ArgoCD syncs the rendered output, not the chart directly.

$ErrorActionPreference = "Stop"

$ChartDir  = "deploy/helm/procurement-spend-dashboard"
$ChartName = "procurement-spend-dashboard"

# tenant, env, namespace — extend here when adding environments
$Envs = @(
  @{ tenant = "cumminsidp"; env = "prod-us-east-1"; ns = "cumminsidp-prod" }
)

if (-not (Get-Command helm -ErrorAction SilentlyContinue)) {
  Write-Error "helm CLI not found. Install Helm 3.x and retry."
  exit 1
}

$repoRoot = (git rev-parse --show-toplevel).Trim()
Set-Location $repoRoot

foreach ($e in $Envs) {
  $valuesFile = Join-Path $ChartDir "values-$($e.env).yaml"
  $outDir     = Join-Path "deployer-apps" "$($e.tenant)/$($e.env)/manifests"
  $outFile    = Join-Path $outDir "$ChartName.yaml"

  if (-not (Test-Path $valuesFile)) {
    Write-Error "Missing values file: $valuesFile"
    exit 1
  }

  New-Item -ItemType Directory -Force -Path $outDir | Out-Null

  Write-Host "Rendering $($e.tenant)/$($e.env) -> $outFile"

  $header = @(
    "# Rendered from $ChartDir/ with"
    "#   values + values-$($e.env).yaml"
    "# Do NOT edit this file by hand. Regenerate via:"
    "#   scripts/render-manifests.ps1"
    "# Tenant: $($e.tenant)   Env: $($e.env)   Namespace: $($e.ns)"
  ) -join "`n"

  $rendered = & helm template $ChartName $ChartDir `
    --namespace $e.ns `
    -f $valuesFile

  if ($LASTEXITCODE -ne 0) {
    Write-Error "helm template failed for $($e.env)"
    exit $LASTEXITCODE
  }

  ($header + "`n" + ($rendered -join "`n")) | Set-Content -Path $outFile -Encoding utf8
  $lineCount = (Get-Content $outFile).Length
  Write-Host "  wrote $lineCount lines"
}

Write-Host ""
Write-Host "Done. Review the diff with: git diff deployer-apps/"
