#!/usr/bin/env bash
# Render the Helm chart at deploy/helm/procurement-spend-dashboard/ into
# deployer-apps/<tenant>/<env>/manifests/ for each tenant+env we ship.
# ArgoCD syncs the rendered output, not the chart directly.
#
# Add new (tenant, env) pairs to the ENVS array below; each pair must
# have a matching values file at
#   deploy/helm/procurement-spend-dashboard/values-<env>.yaml
# and a target path at
#   deployer-apps/<tenant>/<env>/manifests/procurement-spend-dashboard.yaml

set -euo pipefail

CHART_DIR="deploy/helm/procurement-spend-dashboard"
CHART_NAME="procurement-spend-dashboard"

# tenant:env:namespace  (extend here when adding more environments)
ENVS=(
  "cumminsidp:prod-us-east-1:cumminsidp-prod"
)

command -v helm >/dev/null 2>&1 || {
  echo "ERROR: helm CLI not found. Install Helm 3.x and retry." >&2
  exit 1
}

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

for entry in "${ENVS[@]}"; do
  IFS=":" read -r tenant env ns <<<"$entry"
  values_file="${CHART_DIR}/values-${env}.yaml"
  out_dir="deployer-apps/${tenant}/${env}/manifests"
  out_file="${out_dir}/${CHART_NAME}.yaml"

  if [[ ! -f "$values_file" ]]; then
    echo "ERROR: missing values file: $values_file" >&2
    exit 1
  fi

  mkdir -p "$out_dir"

  echo "Rendering ${tenant}/${env} -> ${out_file}"
  {
    echo "# Rendered from ${CHART_DIR}/ with"
    echo "#   values + values-${env}.yaml"
    echo "# Do NOT edit this file by hand. Regenerate via:"
    echo "#   scripts/render-manifests.sh"
    echo "# Tenant: ${tenant}   Env: ${env}   Namespace: ${ns}"
    helm template "$CHART_NAME" "$CHART_DIR" \
      --namespace "$ns" \
      -f "$values_file"
  } >"$out_file"
  echo "  wrote $(wc -l <"$out_file") lines"
done

echo
echo "Done. Review the diff with: git diff deployer-apps/"
